// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/[locale]" | "/[locale]/[legalSlug]" | "/[locale]/account/addresses" | "/[locale]/account/orders" | "/[locale]/account/profile" | "/[locale]/account/wishlist" | "/[locale]/admin" | "/[locale]/admin/blog" | "/[locale]/admin/categories" | "/[locale]/admin/coupons" | "/[locale]/admin/dashboard" | "/[locale]/admin/legal" | "/[locale]/admin/orders" | "/[locale]/admin/orders/[id]" | "/[locale]/admin/payments" | "/[locale]/admin/products" | "/[locale]/admin/products/[id]/edit" | "/[locale]/admin/settings" | "/[locale]/admin/shipping" | "/[locale]/admin/users" | "/[locale]/auth/forgot-password" | "/[locale]/auth/login" | "/[locale]/auth/register" | "/[locale]/auth/reset-password" | "/[locale]/blog" | "/[locale]/blog/[slug]" | "/[locale]/cart" | "/[locale]/category/[slug]" | "/[locale]/checkout" | "/[locale]/checkout/success/[orderId]" | "/[locale]/product/[slug]" | "/[locale]/products"
type AppRouteHandlerRoutes = "/api/auth/[...nextauth]" | "/api/seed-legal" | "/api/storefront/checkout" | "/api/storefront/forgot-password" | "/api/storefront/register" | "/api/storefront/reset-password" | "/api/storefront/reviews" | "/api/storefront/wishlist"
type PageRoutes = never
type LayoutRoutes = "/" | "/[locale]" | "/[locale]/account" | "/[locale]/admin"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/[locale]": { "locale": string; }
  "/[locale]/[legalSlug]": { "locale": string; "legalSlug": string; }
  "/[locale]/account": { "locale": string; }
  "/[locale]/account/addresses": { "locale": string; }
  "/[locale]/account/orders": { "locale": string; }
  "/[locale]/account/profile": { "locale": string; }
  "/[locale]/account/wishlist": { "locale": string; }
  "/[locale]/admin": { "locale": string; }
  "/[locale]/admin/blog": { "locale": string; }
  "/[locale]/admin/categories": { "locale": string; }
  "/[locale]/admin/coupons": { "locale": string; }
  "/[locale]/admin/dashboard": { "locale": string; }
  "/[locale]/admin/legal": { "locale": string; }
  "/[locale]/admin/orders": { "locale": string; }
  "/[locale]/admin/orders/[id]": { "locale": string; "id": string; }
  "/[locale]/admin/payments": { "locale": string; }
  "/[locale]/admin/products": { "locale": string; }
  "/[locale]/admin/products/[id]/edit": { "locale": string; "id": string; }
  "/[locale]/admin/settings": { "locale": string; }
  "/[locale]/admin/shipping": { "locale": string; }
  "/[locale]/admin/users": { "locale": string; }
  "/[locale]/auth/forgot-password": { "locale": string; }
  "/[locale]/auth/login": { "locale": string; }
  "/[locale]/auth/register": { "locale": string; }
  "/[locale]/auth/reset-password": { "locale": string; }
  "/[locale]/blog": { "locale": string; }
  "/[locale]/blog/[slug]": { "locale": string; "slug": string; }
  "/[locale]/cart": { "locale": string; }
  "/[locale]/category/[slug]": { "locale": string; "slug": string; }
  "/[locale]/checkout": { "locale": string; }
  "/[locale]/checkout/success/[orderId]": { "locale": string; "orderId": string; }
  "/[locale]/product/[slug]": { "locale": string; "slug": string; }
  "/[locale]/products": { "locale": string; }
  "/api/auth/[...nextauth]": { "nextauth": string[]; }
  "/api/seed-legal": {}
  "/api/storefront/checkout": {}
  "/api/storefront/forgot-password": {}
  "/api/storefront/register": {}
  "/api/storefront/reset-password": {}
  "/api/storefront/reviews": {}
  "/api/storefront/wishlist": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/[locale]": never
  "/[locale]/account": never
  "/[locale]/admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
