// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/[locale]/(backoffice)/admin/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/blog">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(backoffice)/admin/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(backoffice)/admin/categories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/categories">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(backoffice)/admin/categories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(backoffice)/admin/coupons/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/coupons">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(backoffice)/admin/coupons/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(backoffice)/admin/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(backoffice)/admin/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(backoffice)/admin/legal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/legal">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(backoffice)/admin/legal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(backoffice)/admin/orders/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/orders/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(backoffice)/admin/orders/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(backoffice)/admin/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/orders">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(backoffice)/admin/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(backoffice)/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(backoffice)/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(backoffice)/admin/pages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/pages">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(backoffice)/admin/pages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(backoffice)/admin/payments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/payments">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(backoffice)/admin/payments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(backoffice)/admin/products/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/products/[id]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(backoffice)/admin/products/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(backoffice)/admin/products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/products">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(backoffice)/admin/products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(backoffice)/admin/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/settings">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(backoffice)/admin/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(backoffice)/admin/shipping/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/shipping">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(backoffice)/admin/shipping/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(backoffice)/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/users">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(backoffice)/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(storefront)/[...dynamicSlug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/[...dynamicSlug]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(storefront)/[...dynamicSlug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(storefront)/account/addresses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/account/addresses">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(storefront)/account/addresses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(storefront)/account/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/account/orders">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(storefront)/account/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(storefront)/account/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/account/profile">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(storefront)/account/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(storefront)/account/wishlist/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/account/wishlist">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(storefront)/account/wishlist/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(storefront)/auth/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/auth/forgot-password">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(storefront)/auth/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(storefront)/auth/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/auth/login">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(storefront)/auth/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(storefront)/auth/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/auth/register">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(storefront)/auth/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(storefront)/auth/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/auth/reset-password">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(storefront)/auth/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(storefront)/blog/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/blog/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(storefront)/blog/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(storefront)/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/blog">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(storefront)/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(storefront)/cart/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/cart">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(storefront)/cart/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(storefront)/category/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/category/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(storefront)/category/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(storefront)/checkout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/checkout">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(storefront)/checkout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(storefront)/checkout/success/[orderId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/checkout/success/[orderId]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(storefront)/checkout/success/[orderId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(storefront)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(storefront)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(storefront)/product/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/product/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(storefront)/product/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(storefront)/products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/products">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(storefront)/products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/[...nextauth]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...nextauth]">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/[...nextauth]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/seed-legal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/seed-legal">> = Specific
  const handler = {} as typeof import("../../src/app/api/seed-legal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/storefront/checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/storefront/checkout">> = Specific
  const handler = {} as typeof import("../../src/app/api/storefront/checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/storefront/forgot-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/storefront/forgot-password">> = Specific
  const handler = {} as typeof import("../../src/app/api/storefront/forgot-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/storefront/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/storefront/register">> = Specific
  const handler = {} as typeof import("../../src/app/api/storefront/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/storefront/reset-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/storefront/reset-password">> = Specific
  const handler = {} as typeof import("../../src/app/api/storefront/reset-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/storefront/reviews/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/storefront/reviews">> = Specific
  const handler = {} as typeof import("../../src/app/api/storefront/reviews/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/storefront/wishlist/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/storefront/wishlist">> = Specific
  const handler = {} as typeof import("../../src/app/api/storefront/wishlist/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/[locale]/(backoffice)/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]/admin">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(backoffice)/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(storefront)/account/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]/account">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(storefront)/account/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(storefront)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(storefront)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
