var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/storefront/reviews/route.js")
R.c("server/chunks/[root-of-the-server]__3ecb1c3e._.js")
R.c("server/chunks/[root-of-the-server]__b19a1d45._.js")
R.c("server/chunks/node_modules_bcryptjs_index_42ebb250.js")
R.c("server/chunks/[root-of-the-server]__f408c708._.js")
R.c("server/chunks/_b16832b0._.js")
R.c("server/chunks/_4f846f1e._.js")
R.c("server/chunks/_next-internal_server_app_api_storefront_reviews_route_actions_fa00a0a2.js")
R.m(35432)
module.exports=R.m(35432).exports
