const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

async function main() {
    const page = await prisma.legalPage.upsert({
        where: { slug: 'privacy-policy' },
        update: {},
        create: {
            slug: 'privacy-policy',
            legal_page_translations: {
                create: [
                    { locale: 'es', title: 'Política de Privacidad', content: '<p>Esta es la <strong>política de privacidad</strong> generada por el CMS.</p>' },
                    { locale: 'en', title: 'Privacy Policy', content: '<p>This is the <strong>privacy policy</strong> generated by the CMS.</p>' },
                ]
            }
        }
    });
    console.log('Legal page seeded:', page.slug);
}

main()
    .catch((e) => {
        console.error(e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });
