import { NextResponse } from 'next/server';
import prisma from '@/lib/db';

export async function GET() {
    try {
        const page = await prisma.legalPage.upsert({
            where: { slug: 'privacy-policy' },
            update: {},
            create: {
                slug: 'privacy-policy',
                legal_page_translations: {
                    create: [
                        { locale: 'es', title: 'Política de Privacidad', content: '<p>Esta es la <strong>política de privacidad</strong> generada por el CMS.</p>' },
                        { locale: 'en', title: 'Privacy Policy', content: '<p>This is the <strong>privacy policy</strong> generated by the CMS.</p>' },
                    ]
                }
            }
        });

        const page2 = await prisma.legalPage.upsert({
            where: { slug: 'terms-conditions' },
            update: {},
            create: {
                slug: 'terms-conditions',
                legal_page_translations: {
                    create: [
                        { locale: 'es', title: 'Términos y Condiciones', content: '<p>Estos son los <strong>términos y condiciones</strong> del Storefront.</p>' },
                        { locale: 'en', title: 'Terms and Conditions', content: '<p>These are the <strong>terms and conditions</strong>.</p>' },
                    ]
                }
            }
        });

        return NextResponse.json({ success: true, seeded: [page.slug, page2.slug] });
    } catch (error: any) {
        return NextResponse.json({ error: error.message }, { status: 500 });
    }
}
